version: '3'
services:
  sam:
    image: sam-docker
    ports:
      - "3000:3000"
    working_dir: /project/sam-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - .:/project
